[package]
name = "sb3-builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = { version = "0.7.0", default-features = false }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }
